## iPinYou DataSet EDA

In [1]:
# imports 
import pandas as pd 
import numpy as np

In [2]:
# loading the data 
from ad_causal_doubleml.config.paths import DATA_DIR
file_path = DATA_DIR / "../1458/train.log.txt"

# explicit dtypes reduce memory usage when loading
# the large dataset
dtypes = {
    "click": "int8",
    "weekday": "int8",
    "hour": "int8",
    "logtype": "int8",

    "region": "int16",
    "city": "int16",

    "adexchange": "category",

    "slotwidth": "int16",
    "slotheight": "int16",

    "slotvisibility": "category",
    "slotformat": "int16",

    "slotprice": "int16",

    "bidprice": "int16",
    "payprice": "int16",

    "advertiser": "category",

    # High-cardinality categorical features
    "bidid": "string",
    "timestamp": "string",
    "ipinyouid": "string",
    "useragent": "category",
    "IP": "string",
    "domain": "string",
    "url": "string",
    "urlid": "string",
    "slotid": "string",
    "creative": "string",
    "keypage": "string",
    "usertag": "string"
}

df = pd.read_csv(
    file_path,
    sep="\t",
    dtype=dtypes,
    na_values=["null"]
)

#### Data Shape and Dtypes

In [3]:
print(df.shape)
print(df.dtypes)

(3083056, 27)
click                       int8
weekday                     int8
hour                        int8
bidid             string[python]
timestamp         string[python]
logtype                     int8
ipinyouid         string[python]
useragent               category
IP                string[python]
region                     int16
city                       int16
adexchange              category
domain            string[python]
url               string[python]
urlid             string[python]
slotid            string[python]
slotwidth                  int16
slotheight                 int16
slotvisibility          category
slotformat                 int16
slotprice                  int16
creative          string[python]
bidprice                   int16
payprice                   int16
keypage           string[python]
advertiser              category
usertag           string[python]
dtype: object

#### Missing Values

In [4]:
df.isna().sum().sort_values(ascending=False)

urlid             3083056
usertag            399463
domain             169140
url                 68566
timestamp               0
slotwidth               0
advertiser              0
keypage                 0
payprice                0
bidprice                0
creative                0
slotprice               0
slotformat              0
slotvisibility          0
slotheight              0
slotid                  0
logtype                 0
hour                    0
weekday                 0
bidid                   0
adexchange              0
city                    0
region                  0
IP                      0
useragent               0
ipinyouid               0
click                   0
dtype: int64

Percentage of a feature that is missing:

In [5]:
(df.isna().mean() * 100).sort_values(ascending=False).round(2)

urlid             100.00
usertag            12.96
domain              5.49
url                 2.22
timestamp           0.00
slotwidth           0.00
advertiser          0.00
keypage             0.00
payprice            0.00
bidprice            0.00
creative            0.00
slotprice           0.00
slotformat          0.00
slotvisibility      0.00
slotheight          0.00
slotid              0.00
logtype             0.00
hour                0.00
weekday             0.00
bidid               0.00
adexchange          0.00
city                0.00
region              0.00
IP                  0.00
useragent           0.00
ipinyouid           0.00
click               0.00
dtype: float64

#### Duplicate Records

In [6]:
# the number of completely identical records
print(df.duplicated().sum())
df[df.duplicated()]

1

,click,weekday,hour,bidid,timestamp,logtype,ipinyouid,useragent,IP,region,...,slotheight,slotvisibility,slotformat,slotprice,creative,bidprice,payprice,keypage,advertiser,usertag
1026676,0,6,10,ac2a4c639cbac54d3a2aca8576441621,20130608105218564,1,VhkxO5xALtk4FWc,windows_ie,218.93.21.*,80,...,90,2,0,5,48f2e9ba15708c0146bda5e1dd653caa,300,60,bebefa5efe83beee17a3d245e7c5085b,1458,<NA>

In [7]:
# the duplicated entry 
df[df["bidid"]=="ac2a4c639cbac54d3a2aca8576441621"]
# can see that usertage entry is "<NA>"

,click,weekday,hour,bidid,timestamp,logtype,ipinyouid,useragent,IP,region,...,slotheight,slotvisibility,slotformat,slotprice,creative,bidprice,payprice,keypage,advertiser,usertag
1024054,0,6,10,ac2a4c639cbac54d3a2aca8576441621,20130608104910589,1,VhkxO5xALtk4FWc,windows_ie,218.93.21.*,80,...,90,2,0,5,48f2e9ba15708c0146bda5e1dd653caa,300,60,bebefa5efe83beee17a3d245e7c5085b,1458,<NA>
1025722,0,6,10,ac2a4c639cbac54d3a2aca8576441621,20130608105007505,1,VhkxO5xALtk4FWc,windows_ie,218.93.21.*,80,...,90,2,0,5,48f2e9ba15708c0146bda5e1dd653caa,300,60,bebefa5efe83beee17a3d245e7c5085b,1458,<NA>
1025723,0,6,10,ac2a4c639cbac54d3a2aca8576441621,20130608105048784,1,VhkxO5xALtk4FWc,windows_ie,218.93.21.*,80,...,90,2,0,5,48f2e9ba15708c0146bda5e1dd653caa,300,60,bebefa5efe83beee17a3d245e7c5085b,1458,<NA>
1025724,0,6,10,ac2a4c639cbac54d3a2aca8576441621,20130608105051022,1,VhkxO5xALtk4FWc,windows_ie,218.93.21.*,80,...,90,2,0,5,48f2e9ba15708c0146bda5e1dd653caa,300,60,bebefa5efe83beee17a3d245e7c5085b,1458,<NA>
1026513,0,6,10,ac2a4c639cbac54d3a2aca8576441621,20130608105133520,1,VhkxO5xALtk4FWc,windows_ie,218.93.21.*,80,...,90,2,0,5,48f2e9ba15708c0146bda5e1dd653caa,300,60,bebefa5efe83beee17a3d245e7c5085b,1458,<NA>
1026514,0,6,10,ac2a4c639cbac54d3a2aca8576441621,20130608105133532,1,VhkxO5xALtk4FWc,windows_ie,218.93.21.*,80,...,90,2,0,5,48f2e9ba15708c0146bda5e1dd653caa,300,60,bebefa5efe83beee17a3d245e7c5085b,1458,<NA>
1026522,0,6,10,ac2a4c639cbac54d3a2aca8576441621,20130608105147074,1,VhkxO5xALtk4FWc,windows_ie,218.93.21.*,80,...,90,2,0,5,48f2e9ba15708c0146bda5e1dd653caa,300,60,bebefa5efe83beee17a3d245e7c5085b,1458,<NA>
1026523,0,6,10,ac2a4c639cbac54d3a2aca8576441621,20130608105147104,1,VhkxO5xALtk4FWc,windows_ie,218.93.21.*,80,...,90,2,0,5,48f2e9ba15708c0146bda5e1dd653caa,300,60,bebefa5efe83beee17a3d245e7c5085b,1458,<NA>
1026525,0,6,10,ac2a4c639cbac54d3a2aca8576441621,20130608105159242,1,VhkxO5xALtk4FWc,windows_ie,218.93.21.*,80,...,90,2,0,5,48f2e9ba15708c0146bda5e1dd653caa,300,60,bebefa5efe83beee17a3d245e7c5085b,1458,<NA>
1026526,0,6,10,ac2a4c639cbac54d3a2aca8576441621,20130608105159243,1,VhkxO5xALtk4FWc,windows_ie,218.93.21.*,80,...,90,2,0,5,48f2e9ba15708c0146bda5e1dd653caa,300,60,bebefa5efe83beee17a3d245e7c5085b,1458,<NA>
1026527,0,6,10,ac2a4c639cbac54d3a2aca8576441621,20130608105201930,1,VhkxO5xALtk4FWc,windows_ie,218.93.21.*,80,...,90,2,0,5,48f2e9ba15708c0146bda5e1dd653caa,300,60,bebefa5efe83beee17a3d245e7c5085b,1458,<NA>
1026528,0,6,10,ac2a4c639cbac54d3a2aca8576441621,20130608105201962,1,VhkxO5xALtk4FWc,windows_ie,218.93.21.*,80,...,90,2,0,5,48f2e9ba15708c0146bda5e1dd653caa,300,60,bebefa5efe83beee17a3d245e7c5085b,1458,<NA>
1026529,0,6,10,ac2a4c639cbac54d3a2aca8576441621,20130608105205144,1,VhkxO5xALtk4FWc,windows_ie,218.93.21.*,80,...,90,2,0,5,48f2e9ba15708c0146bda5e1dd653caa,300,60,bebefa5efe83beee17a3d245e7c5085b,1458,<NA>
1026530,0,6,10,ac2a4c639cbac54d3a2aca8576441621,20130608105205153,1,VhkxO5xALtk4FWc,windows_ie,218.93.21.*,80,...,90,2,0,5,48f2e9ba15708c0146bda5e1dd653caa,300,60,bebefa5efe83beee17a3d245e7c5085b,1458,<NA>
1026531,0,6,10,ac2a4c639cbac54d3a2aca8576441621,20130608105209089,1,VhkxO5xALtk4FWc,windows_ie,218.93.21.*,80,...,90,2,0,5,48f2e9ba15708c0146bda5e1dd653caa,300,60,bebefa5efe83beee17a3d245e7c5085b,1458,<NA>
1026532,0,6,10,ac2a4c639cbac54d3a2aca8576441621,20130608105209120,1,VhkxO5xALtk4FWc,windows_ie,218.93.21.*,80,...,90,2,0,5,48f2e9ba15708c0146bda5e1dd653caa,300,60,bebefa5efe83beee17a3d245e7c5085b,1458,<NA>
1026553,0,6,10,ac2a4c639cbac54d3a2aca8576441621,20130608105212809,1,VhkxO5xALtk4FWc,windows_ie,218.93.21.*,80,...,90,2,0,5,48f2e9ba15708c0146bda5e1dd653caa,300,60,bebefa5efe83beee17a3d245e7c5085b,1458,<NA>
1026554,0,6,10,ac2a4c639cbac54d3a2aca8576441621,20130608105212818,1,VhkxO5xALtk4FWc,windows_ie,218.93.21.*,80,...,90,2,0,5,48f2e9ba15708c0146bda5e1dd653caa,300,60,bebefa5efe83beee17a3d245e7c5085b,1458,<NA>
1026675,0,6,10,ac2a4c639cbac54d3a2aca8576441621,20130608105218564,1,VhkxO5xALtk4FWc,windows_ie,218.93.21.*,80,...,90,2,0,5,48f2e9ba15708c0146bda5e1dd653caa,300,60,bebefa5efe83beee17a3d245e7c5085b,1458,<NA>
1026676,0,6,10,ac2a4c639cbac54d3a2aca8576441621,20130608105218564,1,VhkxO5xALtk4FWc,windows_ie,218.93.21.*,80,...,90,2,0,5,48f2e9ba15708c0146bda5e1dd653caa,300,60,bebefa5efe83beee17a3d245e7c5085b,1458,<NA>
1026875,0,6,10,ac2a4c639cbac54d3a2aca8576441621,20130608105221647,1,VhkxO5xALtk4FWc,windows_ie,218.93.21.*,80,...,90,2,0,5,48f2e9ba15708c0146bda5e1dd653caa,300,60,bebefa5efe83beee17a3d245e7c5085b,1458,<NA>
1027084,0,6,10,ac2a4c639cbac54d3a2aca8576441621,20130608105230651,1,VhkxO5xALtk4FWc,windows_ie,218.93.21.*,80,...,90,2,0,5,48f2e9ba15708c0146bda5e1dd653caa,300,60,bebefa5efe83beee17a3d245e7c5085b,1458,<NA>
1027154,0,6,10,ac2a4c639cbac54d3a2aca8576441621,20130608105238650,1,VhkxO5xALtk4FWc,windows_ie,218.93.21.*,80,...,90,2,0,5,48f2e9ba15708c0146bda5e1dd653caa,300,60,bebefa5efe83beee17a3d245e7c5085b,1458,<NA>
1027156,0,6,10,ac2a4c639cbac54d3a2aca8576441621,20130608105238653,1,VhkxO5xALtk4FWc,windows_ie,218.93.21.*,80,...,90,2,0,5,48f2e9ba15708c0146bda5e1dd653caa,300,60,bebefa5efe83beee17a3d245e7c5085b,1458,<NA>

Remove the row that is completely duplicated:

In [8]:
df = df[df["bidid"] != "ac2a4c639cbac54d3a2aca8576441621"]

The number of remaining bid ids

In [9]:
# dataframe containing only duplicated entries
df_duplicated = df[df["bidid"].duplicated(keep=False)]

In [10]:
df_duplicated.shape

(11619, 27)

In [11]:
df_duplicated["bidid"].unique().shape
# this implies duplicate bidids have many rows
# this is the number of rows I aim to end up with
# one row for each unique bidid

(5602,)

Check for empty strings

In [12]:
# check for empty strings 
"""
obj_cols = df.select_dtypes(include='object').columns

(df
    .apply(lambda s: s.astype(str).str.strip().eq('').sum())
    .sort_values(ascending=False))
    """

"\nobj_cols = df.select_dtypes(include='object').columns\n\n(df\n    .apply(lambda s: s.astype(str).str.strip().eq('').sum())\n    .sort_values(ascending=False))\n    "

In [13]:
compare_cols = [c for c in df_duplicated.columns if c != "bidid"]
results = []

# only process duplicated bidid groups

In [14]:
dup_groups = df_duplicated.groupby("bidid").filter(lambda g: len(g) > 1).groupby("bidid")

In [15]:
for bidid, group in dup_groups:
    # Columns where values differ within this bidid
    diff_cols = [col for col in compare_cols if group[col].nunique(dropna=False) > 1]

    if diff_cols:
        # Store differing columns and their values
        diff_values = {
            col: group[col].tolist()
            for col in diff_cols
        }

        results.append({
            "bidid": bidid,
            "different_features": diff_cols,
            "values": diff_values
        })

# Convert to dataframe for easy viewing
diff_df = pd.DataFrame(results)

In [16]:
#print(diff_df)

dict = {}

total_diff_in_timestamps = 0
num_diff_timestamps = 0

from datetime import datetime
# Parse: first 14 digits are yyyyMMddHHmmss, last 3 are milliseconds
def parse_ts(ts: str) -> datetime:
    return datetime.strptime(ts, '%Y%m%d%H%M%S%f')


# Optional: pretty print each bidid
for _, row in diff_df.iterrows():
    print(f"\nBidID: {row['bidid']}")
    print("Different features:", row["different_features"])
    for feature in row["different_features"]:
        if feature in dict:
            dict[feature] += 1
        else:
            dict[feature] = 1
    for feature, values in row["values"].items():
        print(f"  {feature}: {values}")
        if feature == "timestamp":
            #print(int(values[1])-int(values[0]))

            dt1 = parse_ts(values[0])
            dt2 = parse_ts(values[1]) 
            if len(values) > 2:
                print("number of timestamp values more than two")
                break
            delta_s = (dt2 - dt1).total_seconds()

            total_diff_in_timestamps += delta_s
            num_diff_timestamps += 1

BidID: 10017f7b042216349d89dfe7d9ada3a7
Different features: ['timestamp', 'ipinyouid']
  timestamp: ['20130612141014886', '20130612141014982']
  ipinyouid: ['Vh5zPnqmLQb9FBa', 'Vh5zP3p63U8fjQc']

BidID: 1007fdd9a74414192a03c9bd77202a0a
Different features: ['timestamp', 'ipinyouid', 'usertag']
  timestamp: ['20130612204207951', '20130612204208020']
  ipinyouid: ['Vh5zLxl83Q1VJVR', 'Vh5zLxl9OHEIjZa']
  usertag: [<NA>, '10063,10111']

BidID: 100df7877c81acfdf999e1a0ee1eb73f
Different features: ['timestamp', 'ipinyouid', 'usertag']
  timestamp: ['20130612152514254', '20130612152514288']
  ipinyouid: ['Vhk0CDpqD4xUFGn', 'Vh5zPaK6P2F6qhc']
  usertag: ['10006,10110', '10102,10063,10006,10110']

BidID: 1014d5f55911b7186f9af6462c9911f0
Different features: ['timestamp', 'ipinyouid', 'usertag']
  timestamp: ['20130610000104347', '20130610000104486']
  ipinyouid: ['VhkyOaCx3QTLjMR', 'Vh5hZAnxP9T2Xh2']
  usertag: ['10063', <NA>]

BidID: 1014ef29721f3210bbd540fd52e50a3f
Different features: ['timestamp']
  timestamp: ['20130609200010965', '20130609200033260']

BidID: 1031efe9ff6c1d872821a6d6ec13ca07
Different features: ['timestamp', 'ipinyouid']
  timestamp: ['20130612002812954', '20130612002813662']
  ipinyouid: ['Vh5zZndn3QBWwGk', 'Vh5zZndpDt88jV8']

BidID: 103c9a9da4a93fd545761e5552eae1b
Different features: ['timestamp', 'ipinyouid']
  timestamp: ['20130606231325847', '20130606231325910']
  ipinyouid: ['Vhk71edVDUKPFZl', 'Vhk71w113tqZXMB']

BidID: 104ef60d03b89683185c4f5b5d54437b
Different features: ['timestamp', 'ipinyouid']
  timestamp: ['20130609065114576', '20130609065114645']
  ipinyouid: ['VhkyVus6LepTgmf', 'VhkyVus6DelsJVb']

BidID: 1059422481e292a42638c4b5602e7e00
Different features: ['timestamp', 'ipinyouid']
  timestamp: ['20130606223015125', '20130606223024307']
  ipinyouid: ['Vhk71k5HOQc4DMz', 'Vhk71k5LPTK6Ffa']

BidID: 1076f5fcccb33e7118fc4df86b0cd361
Different features: ['timestamp', 'ipinyouid']
  timestamp: ['20130611094410767', '20130611094410939']
  ipinyouid: ['VhkxPeKY36kWj-l', 'Vh5_C5FA3qF6BC2']

BidID: 107f65e07670651f4c92f4c75e2691d3
Different features: ['timestamp']
  timestamp: ['20130607202426615', '20130607202426940']

BidID: 10918de0719202432c9ed09170eeb826
Different features: ['timestamp', 'ipinyouid']
  timestamp: ['20130611044105169', '20130611044105235']
  ipinyouid: ['VhkYLuxPOIs6qMn', 'Vh5_VpkyO9jIkGE']

BidID: 10951a8286737a914cb6ab074b872cf5
Different features: ['timestamp', 'ipinyouid', 'usertag']
  timestamp: ['20130606083710764', '20130606083711276']
  ipinyouid: ['Vhk7Zu5nLqRIMWj', 'Vhk7CppiPHbfBmR']
  usertag: [<NA>, '10063']

BidID: 10a979105df92f827a8c1cbffa4efa39
Different features: ['timestamp', 'ipinyouid', 'usertag']
  timestamp: ['20130612151609189', '20130612151609683']
  ipinyouid: ['Vh1TL5pGP2mPwsR', 'Vh5zPwBIDqjIlVC']
  usertag: ['10063,10110', '10063']

BidID: 10b4506325bac95dfbf6269619288280
Different features: ['timestamp', 'ipinyouid', 'usertag']
  timestamp: ['20130612195109117', '20130612195109382']
  ipinyouid: ['VhkR1A52Lt9Cjb2', 'Vh5zLufIPQb9FBn']
  usertag: ['10059,10063,10006,10110', '10006,10110']

BidID: 10c92f4c0a4ac84c93ff4380d09a90b0
Different features: ['timestamp', 'ipinyouid']
  timestamp: ['20130607000110839', '20130607000111747']
  ipinyouid: ['VhkRZApA36jsQdk', 'VhkRZApiDNjhlhc']

BidID: 10d16db844c9884f814e7bd0778c6b62
Different features: ['timestamp']
  timestamp: ['20130606140715654', '20130606140905865']

BidID: 10d86e26e824ec3828e471c6cb062a14
Different features: ['timestamp']
  timestamp: ['20130609053312382', '20130609053330931']

BidID: 10e1b857ea71adb2436070abe1eecefe
Different features: ['timestamp', 'ipinyouid', 'usertag']
  timestamp: ['20130611004310932', '20130611004311025']
  ipinyouid: ['Vh1_C59TOy16t-B', 'Vh5_ZpMiO2pHGVa']
  usertag: [<NA>, '10063']

BidID: 10e98772f23667ddba8834c2f4693b5
Different features: ['timestamp', 'ipinyouid']
  timestamp: ['20130610173220041', '20130610173220160']
  ipinyouid: ['Vh16LJdxPNCWQOz', 'Vh5hLnMCOcFOwbb']

BidID: 10f62354416ece27e06c07158bc27403
Different features: ['timestamp', 'ipinyouid', 'usertag']
  timestamp: ['20130611023204735', '20130611023204850']
  ipinyouid: ['Vh5_ZaBxDcMVeoL', 'Vh5_ZaBx3HNHqGn']
  usertag: [<NA>, '10063']

BidID: 1101897145a7f27d21bcc3697629cd06
Different features: ['timestamp', 'ipinyouid']
  timestamp: ['20130610140516991', '20130610140517174']
  ipinyouid: ['Vh1DL6dLOIFLXIc', 'Vh5hPD5TONbfkdk']

BidID: 110625affedf5dc3d003aec8c7d0a616
Different features: ['timestamp', 'ipinyouid', 'usertag']
  timestamp: ['20130611153124681', '20130611153124784']
  ipinyouid: ['Vh16LRpPOUsvXVk', 'Vh5_PaqLD4jIJ-C']
  usertag: ['10006', '10063,10006,10110']

BidID: 110e62324758e65c53e313aa7a81b43b
Different features: ['timestamp', 'ipinyouid', 'usertag']
  timestamp: ['20130610224905584', '20130610224905886']
  ipinyouid: ['VhkSOaNu3ldZJMC', 'Vh5h15Ry3ZdCFMf']
  usertag: [<NA>, '10063']

BidID: 110f4efe57e5c403a1933529152804f8
Different features: ['timestamp']
  timestamp: ['20130609190316984', '20130609190317048']

BidID: 1112543bd4ed952865835944d9f6ed32
Different features: ['timestamp', 'ipinyouid', 'usertag']
  timestamp: ['20130609215305279', '20130609215305420']
  ipinyouid: ['Vhk7Lpc7DQsUDsa', 'Vhky16nyPcK2lgk']
  usertag: ['10063,10006', '10063,13403,10110']

BidID: 111b77753328b99ab5144967a4e0a189
Different features: ['timestamp', 'ipinyouid', 'usertag']
  timestamp: ['20130609030006585', '20130609030006935']
  ipinyouid: ['VhkyZrz4LeNPem8', 'VhkyZrz43qLhqCn']
  usertag: [<NA>, '10063']

BidID: 112ee8cd03df99bd97f1d163e2445200
Different features: ['timestamp', 'ipinyouid', 'useragent']
  timestamp: ['20130607195919363', '20130607195919511']
  ipinyouid: ['VhkRPnKiP25fwgC', 'VhkRPnK3LQ5_FMk']
  useragent: ['windows_ie', 'other_other']

BidID: 114d9608b0c3837f8fb54a4b95192377
Different features: ['timestamp', 'ipinyouid']
  timestamp: ['20130606204322836', '20130606204323963']
  ipinyouid: ['VhkEP3mG3cFLQdl', 'Vhk7LxMP3v1Oemc']

BidID: 115173ef64b1af56f19225bb30d90b41
Different features: ['timestamp', 'ipinyouid']
  timestamp: ['20130606093915357', '20130606093915399']
  ipinyouid: ['Vhk7C5dHPqTTGbB', 'Vhk7C5dHPUqOQfC']

BidID: 1155b3e496fc0492326cacf388c8aa63
Different features: ['timestamp']
  timestamp: ['20130611103619581', '20130611103619752']

BidID: 11677dfb7e32ac88c9d257769f98d79b
Different features: ['timestamp', 'ipinyouid']
  timestamp: ['20130608080308511', '20130608080309481']
  ipinyouid: ['Vh1VPuMN3TxZGbL', 'VhkxCACIP8uHJmE']

BidID: 116815489595feaad58362caf48c3c96
Different features: ['timestamp', 'ipinyouid', 'usertag']
  timestamp: ['20130610152318288', '20130610152318341']
  ipinyouid: ['VhkR1JuCOosOe-c', 'Vh5hPw9ZPtSPgIk']
  usertag: [<NA>, '10063']

BidID: 116821a3b71a4831fc0e24aa5caaea13
Different features: ['timestamp', 'ipinyouid', 'usertag']
  timestamp: ['20130611153113766', '20130611153113997']
  ipinyouid: ['Vhd2PedrLQL9lMn', 'Vh5_Paqp3N24Q-C']
  usertag: ['10006,10059,13403,10063,10110', '10006,10110']

BidID: 116db1d2edb33afaafb0621cff17d5f4
Different features: ['timestamp', 'ipinyouid', 'usertag']
  timestamp: ['20130610211903474', '20130610211903570']
  ipinyouid: ['Vhk0L61NONMPwsa', 'Vh5h1icRLZByJWE']
  usertag: ['13866,10063,10006,13403,10111', <NA>]

BidID: 117152fddcd99d85c088483ab64687a2
Different features: ['timestamp', 'ipinyouid', 'usertag']
  timestamp: ['20130607161117353', '20130607161117377']
  ipinyouid: ['VhkRP7TTPlud3sk', 'VhkRPuxw3TNV3Mc']
  usertag: [<NA>, '10110']

BidID: 117e93394faff97a3b9076344e93313
Different features: ['timestamp']
  timestamp: ['20130611071405593', '20130611071508774', '20130611071509038']
number of timestamp values more than two

BidID: 11856f50072a93eec2098ca072a8d294
Different features: ['timestamp', 'ipinyouid', 'usertag']
  timestamp: ['20130607210817983', '20130607210818039']
  ipinyouid: ['Vh13L55bPUqOub2', 'VhkR1AFZOT1TkBB']
  usertag: ['10006,10052,10057,10063,10083,14273,10110', '10083,10057,10006,14273,10110']

BidID: 118ecab250fc476787c672c2e39967d5
Different features: ['timestamp', 'ipinyouid']
  timestamp: ['20130611030204582', '20130611030204673']
  ipinyouid: ['Vh11LypHO2z8kMB', 'Vh5_Zr2xDlu2kMR']

BidID: 1194e3319e8746b03d39bdab93989c18
Different features: ['timestamp', 'ipinyouid', 'usertag']
  timestamp: ['20130607111516762', '20130607111516898']
  ipinyouid: ['VhkROwq2DoM6wM8', 'VhkrLy5cDUdCaGf']
  usertag: [<NA>, '10077']

BidID: 11a5fb7b95ffb6912b8d0c1846c9ef28
Different features: ['timestamp']
  timestamp: ['20130606154612279', '20130606154621461']

BidID: 11aca6a6091f6ce30de3c864eb514924
Different features: ['timestamp']
  timestamp: ['20130611182808299', '20130611182811777']

BidID: 11b424d1c3e53a10a42fbc22111d540b
Different features: ['timestamp', 'ipinyouid', 'usertag']
  timestamp: ['20130608175718314', '20130608175718892']
  ipinyouid: ['Vh1AOwm4OHfWubE', 'VhkxL65Z3ZuZDo2']
  usertag: ['10063,10110', '10063']

BidID: 11c28290b14e2d869aadc6803b0feaf
Different features: ['timestamp', 'ipinyouid']
  timestamp: ['20130609163516248', '20130609163516384']
  ipinyouid: ['Vhkr1DCRLlMTgYc', 'VhkyPRN2PvnfgY2']

BidID: 11d293b375aea577e2bfd0f697b9b8e7
Different features: ['timestamp']
  timestamp: ['20130606101013806', '20130606101058855']

BidID: 11dc9f40c9b1de5704fdf4d51001e549
Different features: ['timestamp', 'ipinyouid']
  timestamp: ['20130609011307751', '20130609011307901']
  ipinyouid: ['Vh1TZpEr3eT_l-a', 'VhkyZ3L83eqLtYE']

BidID: 11e13d865d3b54ec763e0ec7f479bd12
Different features: ['timestamp', 'ipinyouid']
  timestamp: ['20130606114821573', '20130606114828078']
  ipinyouid: ['Vhk7OuSdLZcWFbb', 'Vhk7OuSkOtlyjbj']

BidID: 11f5fded6827d1b54259e36a78cc1dc6
Different features: ['timestamp', 'ipinyouid', 'usertag']
  timestamp: ['20130608211808176', '20130608211817233']
  ipinyouid: ['Vhkx1ia9ONSCtGR', 'VhkROu5k3cnIJmj']
  usertag: [<NA>, '10006,13403,10063,10110']

BidID: 11f668d816f3127097883392ba28b01d
Different features: ['timestamp', 'ipinyouid', 'usertag']
  timestamp: ['20130611233006469', '20130611233006675']
  ipinyouid: ['Vh5_1ak4P4R8XQj', 'Vh5_1ak4DlbIjQL']
  usertag: [<NA>, '10006,10110']

BidID: 11feea8b5c51818de31e5d3f31671341
Different features: ['timestamp', 'ipinyouid']
  timestamp: ['20130609200009351', '20130609200009444']
  ipinyouid: ['VhkyLrzIPlB9FQb', 'Vhk7L5pNDc2ykGj']

BidID: 120587991651831a1114ebe9165648b0
Different features: ['timestamp', 'ipinyouid']
  timestamp: ['20130608165914670', '20130608165914798']
  ipinyouid: ['VhkxPyM6Dlq2QmE', 'VhkxPyM6D8lswsb']

BidID: 1209cc27295035a9a3b452eda5aa8e85
Different features: ['timestamp', 'ipinyouid', 'usertag']
  timestamp: ['20130612164312327', '20130612164312508']
  ipinyouid: ['Vh5zPxMnPeMHG-E', 'Vhk01wMHPZFO3fn']
  usertag: [<NA>, '13866,10063,10006']

BidID: 12153bbdaa9e895a3cda9714e78e6602
Different features: ['timestamp', 'ipinyouid']
  timestamp: ['20130611031707174', '20130611031707219']
  ipinyouid: ['Vh5_Z7j8ONm2gME', 'Vh5_Z7n8Dq1TqhB']

BidID: 1215e778df2d97aca683a2ca35ab1045
Different features: ['timestamp', 'ipinyouid', 'usertag']
  timestamp: ['20130607215318217', '20130607215318453']
  ipinyouid: ['Vh1Z139RPqKVtbl', 'VhkR16pZPyl4thc']
  usertag: ['10006,10063,10083,10110', '10063']

BidID: 121f440b1628e6024501695d0dc55810
Different features: ['timestamp', 'ipinyouid', 'usertag']
  timestamp: ['20130606002012186', '20130606002012370']
  ipinyouid: ['VhkYPnayO2bs3M8', 'Vhk7ZimnPqf9tGj']
  usertag: ['10063', '13866,10111']

BidID: 123bd6a9262de2d8e8ae450f8d4bae38
Different features: ['timestamp', 'ipinyouid', 'usertag']
  timestamp: ['20130612094212270', '20130612094212611']
  ipinyouid: ['VhkRPruvOecytML', 'Vh5zC5qnLlb8jbn']
  usertag: [<NA>, '10063']

BidID: 12431ac4196aabbb8c1151fe615d6988
Different features: ['timestamp', 'ipinyouid', 'usertag']
  timestamp: ['20130608102314764', '20130608102314843']
  ipinyouid: ['VhkxO396Doa8jdE', 'VhkEL6dAPIfyFCa']
  usertag: [<NA>, '10063']

BidID: 124b31927c7816081bf08abe130f9920
Different features: ['timestamp']
  timestamp: ['20130607150310739', '20130607150459681']

BidID: 124d2ca0464a75b29d5f254243917313
Different features: ['timestamp', 'ipinyouid']
  timestamp: ['20130609020605927', '20130609020606047']
  ipinyouid: ['Vh13CimQDtF6wBb', 'VhkyZJl4OTSLDQl']

BidID: 125324667d7bc81f694b559ff5421077
Different features: ['timestamp', 'ipinyouid']
  timestamp: ['20130612042303894', '20130612042304074']
  ipinyouid: ['Vh5zVi8R3ZmO3ML', 'Vh5zVi8xOt2hebj']

BidID: 1257d1cc350bbc3e7b21e267fcb6c31d
Different features: ['timestamp', 'ipinyouid', 'usertag']
  timestamp: ['20130610092817289', '20130610092817483']
  ipinyouid: ['Vh5hCp5rO42sJhz', 'Vh5hCkdTP8b9GVl']
  usertag: ['13866,10111', <NA>]

BidID: 125fdf5baf0348fb45e0d3ec2d25c42b
Different features: ['timestamp', 'ipinyouid']
  timestamp: ['20130608113111740', '20130608113111880']
  ipinyouid: ['VhkRZakSDlN_g-8', 'VhkxOaqi3Txdegl']

BidID: 126b3764ba5d1a22cfd254f34c912b5d
Different features: ['timestamp', 'ipinyouid', 'usertag']
  timestamp: ['20130606094212403', '20130606094213380']
  ipinyouid: ['Vh1HP3NdLeF_tVC', 'Vhk7C5qpPQa9MWk']
  usertag: ['13496,10063,13776,10093', '10063']

BidID: 127d40e77ca618d9382a7a10f63cd47b
Different features: ['timestamp', 'ipinyouid', 'usertag']
  timestamp: ['20130612005707274', '20130612005707678']
  ipinyouid: ['Vh5zZ6k8PHchqML', 'Vh5zZ6k8DqdZXMb']
  usertag: [<NA>, '10063']

BidID: 12906b7eb74bcc286a0804aebbc64e08
Different features: ['timestamp']
  timestamp: ['20130612081006761', '20130612081006952']

BidID: 12a446ddad4a7a288807dd302df60ce4
Different features: ['timestamp', 'ipinyouid', 'usertag']
  timestamp: ['20130609123114776', '20130609123114865']
  ipinyouid: ['VhkYOxc9L2usjm8', 'VhkyORq632uCqgB']
  usertag: ['10006,10063,10110', '10063,10006,10110']

BidID: 12a5016b93ac3df966b4141edd7531c1
Different features: ['timestamp']
  timestamp: ['20130608174217365', '20130608174217480']

BidID: 12aa49c7762419298517e8ab80787aa8
Different features: ['timestamp']
  timestamp: ['20130610183215265', '20130610183217274']

BidID: 12bc7a19589ebdb229d5001e3ffdf763
Different features: ['timestamp', 'ipinyouid']
  timestamp: ['20130612192805071', '20130612192806430']
  ipinyouid: ['Vh5zLaCyOeFHl-z', 'Vh5zLaC4PNm6Qsl']

BidID: 12c0fdce8bb4aab27520f0f4a3c089bf
Different features: ['timestamp', 'ipinyouid']
  timestamp: ['20130609095720610', '20130609095720772']
  ipinyouid: ['VhkxOxNHPlByaoC', 'VhkyCe5CDy52aoa']

BidID: 12c6aa4be9b820e6680fbb46af201f70
Different features: ['timestamp', 'ipinyouid']
  timestamp: ['20130606163320082', '20130606163329276']
  ipinyouid: ['VhkrPp5qO21_kG8', 'Vhk7PRF5PHE9uYz']

BidID: 12caf28ab1647b560ca5b88aa3ca97c5
Different features: ['timestamp', 'ipinyouid']
  timestamp: ['20130607221612889', '20130607221613116']
  ipinyouid: ['Vh111p9jDQpfJ-C', 'VhkR13MpOQpLuYl']

BidID: 12cfcb420fc63a3f5da7663278664ab8
Different features: ['timestamp', 'ipinyouid', 'usertag']
  timestamp: ['20130606233013458', '20130606233013560']
  ipinyouid: ['Vhk71a5pP428FWl', 'Vhk71a5pLTRywMa']
  usertag: [<NA>, '10006,10110']

BidID: 12f74b7a327b0105e9580efe3716e04b
Different features: ['timestamp']
  timestamp: ['20130611233407604', '20130611233413317', '20130611233419802', '20130611233428844']
number of timestamp values more than two

BidID: 12fdf1e26dcaf3f4a522d82f554261ee
Different features: ['timestamp', 'ipinyouid', 'usertag']
  timestamp: ['20130610060606080', '20130610060606166']
  ipinyouid: ['Vh5hVJl4OtFCt-n', 'Vh5hVJl4ONd6JBj']
  usertag: [<NA>, '10063']

BidID: 130e9cb3dcbb15ba185a87da5c65e57d
Different features: ['timestamp']
  timestamp: ['20130606160022907', '20130606160033402', '20130606160035651']
number of timestamp values more than two

BidID: 131614684ce1525c83cf277ad4b4850c
Different features: ['timestamp', 'ipinyouid']
  timestamp: ['20130611110213306', '20130611110213341']
  ipinyouid: ['Vh1PPiqCD9jsQdf', 'Vh5_OJTpPtxTamz']

BidID: 132bbc743278cb9a317b8efe95ace99c
Different features: ['timestamp', 'ipinyouid', 'usertag']
  timestamp: ['20130609225206871', '20130609225210477']
  ipinyouid: ['Vhky1ez43T1HXZB', 'Vhky1eKAP85PBbC']
  usertag: [<NA>, '10006,10063']

BidID: 13313f2a7edf4d9d9ec40a4182897836
Different features: ['timestamp']
  timestamp: ['20130611224809187', '20130611224814416']

BidID: 13377c6e461d7f83e7d2be78ec2a4d04
Different features: ['timestamp', 'ipinyouid', 'usertag']
  timestamp: ['20130612211504102', '20130612211504322']
  ipinyouid: ['Vh5zOJ1xOlmcXOC', 'Vh5z1ilxPedPj-z']
  usertag: ['10006', '10006,10110']

BidID: 13464737618fc60b541e16018f5b3c42
Different features: ['timestamp', 'ipinyouid', 'usertag']
  timestamp: ['20130610215911445', '20130610215911935']
  ipinyouid: ['Vh5h1AkIOImLeIB', 'Vh5h16Mi3qLIBCk']
  usertag: [<NA>, '10063']

BidID: 13501287c9fd7b1b868c22afeb358cd5
Different features: ['timestamp']
  timestamp: ['20130608203014556', '20130608203046395']

BidID: 13510bc4b8542660952c4974403c5da4
Different features: ['timestamp', 'ipinyouid', 'usertag']
  timestamp: ['20130608140318356', '20130608140318539']
  ipinyouid: ['VhkxP6KvPtdUlgz', 'VhkxPDdZL2dHDdR']
  usertag: ['10006', '10006,10110']

BidID: 136a66e0e4b7ee0aaa49ada6a0d98424
Different features: ['timestamp', 'ipinyouid', 'usertag']
  timestamp: ['20130611140808964', '20130611140809114']
  ipinyouid: ['VhkxZ7RxDICsBMl', 'Vh5_PDjIOqfhQOl']
  usertag: ['10063,10083,10110', '10063,10006,13403']

BidID: 136aab5373d1c05dd1d4c9d2f468d853
Different features: ['timestamp', 'ipinyouid', 'usertag']
  timestamp: ['20130612220302638', '20130612220302675']
  ipinyouid: ['Vh5z1DC7LQb4JOc', 'Vh5z1DC7DlmLlBE']
  usertag: ['10063', <NA>]

BidID: 1370c7ef7f7557edd4e281cea08c3477
Different features: ['timestamp', 'ipinyouid', 'usertag']
  timestamp: ['20130607032309952', '20130607032310105']
  ipinyouid: ['VhkRZ78I3Q5CBZC', 'VhkRZ79AOqqHtMc']
  usertag: [<NA>, '10063']

BidID: 1374145eedf6bed694e8a65e928f6e7a
Different features: ['timestamp', 'ipinyouid', 'usertag']
  timestamp: ['20130611193009765', '20130611193009997']
  ipinyouid: ['Vh1L1iBRLTMvg-j', 'Vh5_LakI3N293gL']
  usertag: ['10006', '13403']

BidID: 137821bd3d515393e60d16147858b5d6
Different features: ['timestamp', 'ipinyouid']
  timestamp: ['20130608034707984', '20130608034809376']
  ipinyouid: ['VhkxZxb83Uz8G-b', 'VhkxZxEIPQk4Bdz']

BidID: 137ea859acdd72e2866b3dad83f0afbe
Different features: ['timestamp']
  timestamp: ['20130609092217618', '20130609092246546', '20130609092250573']
number of timestamp values more than two

BidID: 13ac3c8e596418dbf745f93e59695df4
Different features: ['timestamp', 'ipinyouid']
  timestamp: ['20130612164310641', '20130612164310723']
  ipinyouid: ['Vh5zPxMADe2stOj', 'Vh1DPum3O6cyGYL']

BidID: 13b16362193a2b94f12e5da13449fb3
Different features: ['timestamp', 'ipinyouid', 'usertag']
  timestamp: ['20130610125812768', '20130610125812867']
  ipinyouid: ['Vh5hOyqnDynWw-b', 'VhdLCiSZPob8qYk']
  usertag: [<NA>, '10063,10083,10110']

BidID: 13c0041850dd59626421aa3d694f728c
Different features: ['timestamp', 'ipinyouid']
  timestamp: ['20130611110213083', '20130611110213105']
  ipinyouid: ['Vh5_OJTpOtmTamE', 'Vh5_OJTpOqqClmc']

BidID: 13c8bb1c2fe13dc5450946d95195d95a
Different features: ['timestamp']
  timestamp: ['20130607001013021', '20130607001013099']

BidID: 13cda40fbd22b7062f55c218d4a8fa37
Different features: ['timestamp', 'ipinyouid', 'usertag']
  timestamp: ['20130610222805172', '20130610222805374']
  ipinyouid: ['Vh1116KqDtxPaVB', 'Vh5h1kCyPQCW3Gf']
  usertag: [<NA>, '10063']

BidID: 13d97fe75d41da6c3b9d2f86b224c02e
Different features: ['timestamp', 'ipinyouid', 'usertag']
  timestamp: ['20130612151608044', '20130612151608182']
  ipinyouid: ['Vh1VPvdQOINTQmc', 'Vh5zPwB9OoCsGmk']
  usertag: [<NA>, '10063']

BidID: 13dcb005e19ba73361642acaa3accdee
Different features: ['timestamp']
  timestamp: ['20130611145611838', '20130611145624145']

BidID: 13dff55a332692c9c3bfdf5b0425b3f9
Different features: ['timestamp', 'ipinyouid', 'usertag']
  timestamp: ['20130610111911748', '20130610111920806']

In [17]:
dict

{'timestamp': 5584,
 'ipinyouid': 4146,
 'usertag': 2590,
 'useragent': 180,
 'hour': 48,
 'weekday': 1,
 'payprice': 8}

Removing null usertags

In [18]:
# seperating the rows into where usertag is null 
df_duplicated_temp = df_duplicated
print(df_duplicated_temp.shape)

df_usertag_null = df_duplicated_temp[df_duplicated_temp["usertag"].isna()]
print(f"The number of null usertags is {df_usertag_null['bidid'].count()}")
df_usertag_not_null = df_duplicated_temp[df_duplicated_temp["usertag"].notna()]
# retain nulls where bid id is in not nulls
df_usertag_null = df_usertag_null[df_usertag_null['bidid'].isin(df_usertag_not_null['bidid'])]
print(f"The number of null usertags where there is a non-null usertag is: {df_usertag_null.shape[0]}")


# drop all rows in df_duplicated_temp that appear in df_usertag_null
result = df_duplicated_temp.merge(df_usertag_null.drop_duplicates(), how='left', indicator=True)
df_duplicated_temp = result = result[result['_merge'] == 'left_only'].drop(columns='_merge')
df_duplicated_temp.shape

(11619, 27)
The number of null usertags is 4458
The number of null usertags where there is a non-null usertag is: 1841

(9778, 27)

In [19]:
df_duplicated = df_duplicated_temp

Where the only difference between rows is the timestamp and ipinyouid, retain the row with the later timestamp

In [20]:
import pandas as pd

# Make a copy
df_clean = df_duplicated.copy()

# Convert timestamp to datetime
df_clean["timestamp_dt"] = pd.to_datetime(
    df_clean["timestamp"].astype(str),
    format="%Y%m%d%H%M%S%f"
)

# Columns that must be identical for two rows to be considered duplicates
compare_cols = [
    col for col in df_clean.columns
    if col not in ["timestamp", "ipinyouid", "timestamp_dt"]
]

# Sort by timestamp so the newest row comes first
df_clean = df_clean.sort_values("timestamp_dt", ascending=False)

# Remove duplicates where every column except timestamp and iPinYouid
# is identical. The newest timestamp is retained.
df_clean = df_clean.drop_duplicates(
    subset=compare_cols,
    keep="first"
)

# Remove helper column
df_clean = df_clean.drop(columns="timestamp_dt")

# Reset index
df_clean = df_clean.reset_index(drop=True)

In [21]:
print(f"The number of rows removed where the only difference was the timestamp \nand ipinyouid: {df_duplicated.shape[0]-df_clean.shape[0]}. The older timestamp record is retained.")

The number of rows removed where the only difference was the timestamp
and ipinyouid: 3354. The older timestamp record is retained.

In [22]:
df_duplicated = df_clean
df_duplicated.shape

(6424, 27)

Average difference in timestamps when there are more than one timestamp:

In [23]:
print(f"Average difference in timestamps when there is more than one \ntimestemp for a given bid id: {total_diff_in_timestamps / num_diff_timestamps}.")

Average difference in timestamps when there is more than one
timestemp for a given bid id: 20.289536302395234.

In [24]:
# Parse function
def parse_ts(ts):
    return datetime.strptime(ts, '%Y%m%d%H%M%S%f')

# Convert all timestamps
dts = [parse_ts(ts) for ts in df["timestamp"]]

# Find min and max
min_dt = min(dts)
max_dt = max(dts)

# Difference in seconds
diff_seconds = (max_dt - min_dt).total_seconds()

print('Min:', min_dt)
print('Max:', max_dt)
print('Difference (seconds):', diff_seconds)

Min: 2013-06-06 00:01:04.828000
Max: 2013-06-12 23:42:04.173000
Difference (seconds): 603659.345

In [25]:
results = []
dup_groups = df_duplicated.groupby("bidid").filter(lambda g: len(g) > 1).groupby("bidid")
for bidid, group in dup_groups:
    # Columns where values differ within this bidid
    diff_cols = [col for col in compare_cols if group[col].nunique(dropna=False) > 1]

    if diff_cols:
        # Store differing columns and their values
        diff_values = {
            col: group[col].tolist()
            for col in diff_cols
        }

        results.append({
            "bidid": bidid,
            "different_features": diff_cols,
            "values": diff_values
        })

# Convert to dataframe for easy viewing
diff_df = pd.DataFrame(results)

#print(diff_df)

dict = {}

total_diff_in_timestamps = 0
num_diff_timestamps = 0

from datetime import datetime
# Parse: first 14 digits are yyyyMMddHHmmss, last 3 are milliseconds
def parse_ts(ts: str) -> datetime:
    return datetime.strptime(ts, '%Y%m%d%H%M%S%f')


# Optional: pretty print each bidid
for _, row in diff_df.iterrows():
    print(f"\nBidID: {row['bidid']}")
    print("Different features:", row["different_features"])
    for feature in row["different_features"]:
        if feature in dict:
            dict[feature] += 1
        else:
            dict[feature] = 1
    for feature, values in row["values"].items():
        print(f"  {feature}: {values}")

BidID: 100df7877c81acfdf999e1a0ee1eb73f
Different features: ['usertag']
  usertag: ['10102,10063,10006,10110', '10006,10110']

BidID: 10a979105df92f827a8c1cbffa4efa39
Different features: ['usertag']
  usertag: ['10063', '10063,10110']

BidID: 10b4506325bac95dfbf6269619288280
Different features: ['usertag']
  usertag: ['10006,10110', '10059,10063,10006,10110']

BidID: 110625affedf5dc3d003aec8c7d0a616
Different features: ['usertag']
  usertag: ['10063,10006,10110', '10006']

BidID: 1112543bd4ed952865835944d9f6ed32
Different features: ['usertag']
  usertag: ['10063,13403,10110', '10063,10006']

BidID: 112ee8cd03df99bd97f1d163e2445200
Different features: ['useragent']
  useragent: ['other_other', 'windows_ie']

BidID: 116821a3b71a4831fc0e24aa5caaea13
Different features: ['usertag']
  usertag: ['10006,10110', '10006,10059,13403,10063,10110']

BidID: 11856f50072a93eec2098ca072a8d294
Different features: ['usertag']
  usertag: ['10083,10057,10006,14273,10110', '10006,10052,10057,10063,10083,14273,10110']

BidID: 11b424d1c3e53a10a42fbc22111d540b
Different features: ['usertag']
  usertag: ['10063', '10063,10110']

BidID: 1215e778df2d97aca683a2ca35ab1045
Different features: ['usertag']
  usertag: ['10063', '10006,10063,10083,10110']

BidID: 121f440b1628e6024501695d0dc55810
Different features: ['usertag']
  usertag: ['13866,10111', '10063']

BidID: 126b3764ba5d1a22cfd254f34c912b5d
Different features: ['usertag']
  usertag: ['10063', '13496,10063,13776,10093']

BidID: 12a446ddad4a7a288807dd302df60ce4
Different features: ['usertag']
  usertag: ['10063,10006,10110', '10006,10063,10110']

BidID: 13377c6e461d7f83e7d2be78ec2a4d04
Different features: ['usertag']
  usertag: ['10006,10110', '10006']

BidID: 13510bc4b8542660952c4974403c5da4
Different features: ['usertag']
  usertag: ['10006,10110', '10006']

BidID: 136a66e0e4b7ee0aaa49ada6a0d98424
Different features: ['usertag']
  usertag: ['10063,10006,13403', '10063,10083,10110']

BidID: 1374145eedf6bed694e8a65e928f6e7a
Different features: ['usertag']
  usertag: ['13403', '10006']

BidID: 13dff55a332692c9c3bfdf5b0425b3f9
Different features: ['usertag']
  usertag: ['10006,10110', '10063,10077,10083,10006,10057,10110']

BidID: 141c9aeba0cee4d95cf67239808c5fb5
Different features: ['useragent', 'usertag']
  useragent: ['windows_ie', 'other_other']
  usertag: ['10093,10063,10031,10006,13496,13866,10057,10110', '13866']

BidID: 14495bb88b31e9fc7733510570f97487
Different features: ['usertag']
  usertag: ['10083,13403,10006,10110', '10077,10031,10006,10063,10059,10083,10110']

BidID: 14d838f53012606a53e5acb6fbc92f10
Different features: ['usertag']
  usertag: ['10063', '10063,10075,10076']

BidID: 156b80a4c881309a2cb1ae5ea7879c59
Different features: ['usertag']
  usertag: ['10063,10110', '10031,10057,10059,10077,10006,10063,13403,10111']

BidID: 15772f57df3dedacf0a55fcf67213828
Different features: ['usertag']
  usertag: ['10006,10110', '10111']

BidID: 16137ba5a647cfa83a6a80dc643dc55d
Different features: ['usertag']
  usertag: ['10006,10110', '10063,10006,10083,10110']

BidID: 1630b6dd27613b2cacb9767cba648145
Different features: ['usertag']
  usertag: ['10006,10110', '10006']

BidID: 163efa010826d4d62d1bc8807be6c6dc
Different features: ['usertag']
  usertag: ['13800', '10063,10006,13800,10059,10111']

BidID: 1641991fc4c35c032ece1e5c26dc8a2d
Different features: ['usertag']
  usertag: ['13866,10111', '13866,10063,10111']

BidID: 1669b7683f3295aa7b2c0fa6233ecc9b
Different features: ['usertag']
  usertag: ['10006,10110', '10075,10006,10076,10063,10110']

BidID: 16834bda9ce5e37248aae03bc5365a03
Different features: ['hour']
  hour: [17, 16]

BidID: 16c7bd0c35a2fc3573124740f765e5e5
Different features: ['hour', 'usertag']
  hour: [16, 15]
  usertag: ['14273,10059,10077,10063,10024,10083,10006,10110', '14273']

BidID: 16e6b4c5e3651dc599b878a3b8b6e63c
Different features: ['usertag']
  usertag: ['10006,10110', '10052,10006,10075,10057,10063,14273,10059,10083,10110']

BidID: 17cdfe29e2559649172d9191eca2841c
Different features: ['usertag']
  usertag: ['10006,10110', '10059,10024,10006,10111']

BidID: 17dc772eba08750eea1cdd589260ebad
Different features: ['usertag']
  usertag: ['13866,10111', '13866,10063,13776,10111']

BidID: 17ed45e1ea34e75576a7a39480cdaaa2
Different features: ['usertag']
  usertag: ['10076,13776', '10052,10063,10024,10006,10031,13403,10110']

BidID: 188ee313974ba0ec327ab2b0ed62ca8a
Different features: ['useragent', 'usertag']
  useragent: ['other_other', 'windows_ie']
  usertag: ['10083,10057,10077,10063,13866,10110', '10083,10063,10110']

BidID: 18a1e4b90ecd0eb6a0252ab8ad4ffcca
Different features: ['usertag']
  usertag: ['10006,10110', '10063,10111']

BidID: 196264b83e7a85badf17dd5575516ffb
Different features: ['usertag']
  usertag: ['10063', '13403,10063,10031,10083,10006,10110']

BidID: 1a30b7ddcb0490b4bcae331da82cdbf8
Different features: ['usertag']
  usertag: ['10083,10110', '10006,10102,10083,10063,10110']

BidID: 1a92be4f87f3e1621eb6b12b787d4986
Different features: ['usertag']
  usertag: ['10006,10110', '10031,10024,10057,13042,10076,10075,10079,10006,10063,10110']

BidID: 1aa382e74f603384f8ec76b7f03a478c
Different features: ['useragent', 'usertag']
  useragent: ['other_other', 'windows_ie']
  usertag: ['13866,10111', '13866,10063,10111']

BidID: 1afcdb61e725ae296c2c4d0c72619e99
Different features: ['hour']
  hour: [4, 3]

BidID: 1b2d5ed1c58cc1e39ff810b894359bee
Different features: ['usertag']
  usertag: ['10063,10110', '10063']

BidID: 1b59f40fac92d674a90ee7dbea258e35
Different features: ['usertag']
  usertag: ['10063,13866,10111', '10024,10063,13866,10111']

BidID: 1bbcb0c47999be6eb7cd044d13483e41
Different features: ['usertag']
  usertag: ['10024', '10024,10111']

BidID: 1bdae901060ec0a7ea5a49cf27a4b0ce
Different features: ['useragent']
  useragent: ['other_other', 'windows_ie']

BidID: 1c85121d7eb297029d41db8fceecf3c5
Different features: ['useragent', 'usertag']
  useragent: ['other_other', 'windows_ie']
  usertag: ['10075', '10063,10059,10075,10111']

BidID: 1c89dccab8a504b02343a44a5d293cc7
Different features: ['hour']
  hour: [23, 22]

BidID: 1c98847bf4d912d7369db3182365ed42
Different features: ['usertag']
  usertag: ['10063,10006', '10063']

BidID: 1cbfa6ccc6687ba36166d382489b2010
Different features: ['usertag']
  usertag: ['10063,10006,10110', '10006,10063,10110']

BidID: 1d6b140e7fbc7c6f28af04446d97b33f
Different features: ['usertag']
  usertag: ['10006,10110', '10063']

BidID: 1dbcc8d74ab22ee90bc59260a0d5250
Different features: ['usertag']
  usertag: ['10063', '10059,10111']

BidID: 1dc085958a99b294c3ab65641802c94
Different features: ['usertag']
  usertag: ['10006,10110', '10077,10063,13776,10031,10006,10110']

BidID: 1dd5b5f79a734998f4156cd6fe1ca708
Different features: ['usertag']
  usertag: ['10063', '10006,10063']

BidID: 1df3f1dd9930324837eb4c2ca9ed1b7d
Different features: ['usertag']
  usertag: ['10063', '10063,10006']

BidID: 1e1180e1d2a4da21c943453bd1f61cee
Different features: ['usertag']
  usertag: ['10006,10110', '10059,10079,10052,10063,10077,10006,10075,10111']

BidID: 1ea4ac0e24827b9869ff733cc236b710
Different features: ['usertag']
  usertag: ['10063,10006,10110', '10006,10110']

BidID: 1f3440544251f695c57c64d6f3ec8314
Different features: ['hour', 'useragent']
  hour: [9, 8]
  useragent: ['other_other', 'windows_ie']

BidID: 1f66430d74bc0d50e6a92c11ea9b3490
Different features: ['usertag']
  usertag: ['10063', '10057,10083,10075,10052,10059,10024,13403,10063,10077,10006,10111']

BidID: 1fa93645da563b119a65a7e8b4399133
Different features: ['usertag']
  usertag: ['13866,10111', '10063,13866,10024,10111']

BidID: 2027c360557aee18706e0a467ba9164c
Different features: ['useragent', 'usertag']
  useragent: ['other_other', 'windows_ie']
  usertag: ['10006,10052,10083,10063,10110', '10063,14273,10006,10083,10077,10110']

BidID: 20840894cdcb007779c9e63d24006af9
Different features: ['usertag']
  usertag: ['10006,10063,10110', '10006,10052,14273,10048,10031,10063,10684,10083,13042,10110']

BidID: 209e2cc283ee45879b543447207bf504
Different features: ['useragent', 'usertag']
  useragent: ['windows_chrome', 'windows_ie']
  usertag: ['10006,10063,10110', '10079,10075,10006,10110']

BidID: 20cbdac1dafd5cd1a8716a1dc69a77c3
Different features: ['usertag']
  usertag: ['10063,10006,10110', '10063,10006,10111']

BidID: 2105ffbe8a5d1c2af39b9617cba93859
Different features: ['usertag']
  usertag: ['10006,10110', '10024,10052,10063,13678,10006,10057,10110']

BidID: 213d7d3c458468bc8b74e4548e7455f7
Different features: ['usertag']
  usertag: ['13866,10111', '10063,10024,13866']

BidID: 217fa68a43f2bfbc79177a65a34712
Different features: ['usertag']
  usertag: ['10063', '10063,10111']

BidID: 219ec7c1ec5b961e70d4024e48b18e49
Different features: ['usertag']
  usertag: ['10083,10110', '10063']

BidID: 21eb1f349b59ebdbf0af86108d75b00b
Different features: ['useragent']
  useragent: ['other_other', 'windows_ie']

BidID: 22360bf6148677e341187aa89eb5570b
Different features: ['usertag']
  usertag: ['10075,10063', '10006']

BidID: 22af55ae019bfd7c6410bcb3804d996d
Different features: ['useragent', 'usertag']
  useragent: ['other_other', 'windows_ie']
  usertag: ['10006', '10083,10063,10052,10075,10006,10057,10110']

BidID: 23114d1077e9e9cfcd81752f35861d08
Different features: ['usertag']
  usertag: ['10063,13866,10110', '10006']

BidID: 235a4c6cd5d6a95bc92570ddec9b8313
Different features: ['usertag']
  usertag: ['13866,10111', '13866,10063,10111']

BidID: 237e0afb5b17a21faa9ab48dd0346e68
Different features: ['useragent']
  useragent: ['other_other', 'android_safari']

BidID: 23d8cfb0c1e237e55879a8c1e5457917
Different features: ['usertag']
  usertag: ['10006,10110', '10006']

BidID: 23da1cf1bceef178269f2170bfc057f3
Different features: ['usertag']
  usertag: ['10063', '10006']

BidID: 24262bef3ed808d2c691690460462da9
Different features: ['usertag']
  usertag: ['10063', '13496,10063,13776,10093']

BidID: 2483b649edcd202f78ea1863c722209a
Different features: ['usertag']
  usertag: ['10006,10110', '10063,10083,10006,10059,10057,10031,10110']

BidID: 248a404a1147ecf0fa5280f68d48d3d2
Different features: ['usertag']
  usertag: ['10006,10110', '10063,13403,10059,10075,10024,14273,10031,10076,10083,10052,10093,10006,10048,10074,10110']

BidID: 249dbe235b54cbde8905fb587f260efe
Different features: ['usertag']
  usertag: ['10063', '10111']

BidID: 24ccec38afb6280c927be1263ea2fa8d
Different features: ['usertag']
  usertag: ['13866', '13866,10083,10024,10063,10006,10110']

BidID: 24dab07c807c397f6c22ebbe5416d0a7
Different features: ['usertag']
  usertag: ['10006,10110', '10063,10075']

BidID: 250e9279cade4c02a7ecbe9dd5f8168e
Different features: ['useragent', 'usertag']
  useragent: ['other_other', 'windows_ie']
  usertag: ['13866,10111', '10075,10059,10063,13866,10111']

BidID: 252eecfbbbd24fb3c411d630a96aa9e3
Different features: ['usertag']
  usertag: ['10063', '14273']

BidID: 25940804171154cc73a713bddbcf17a5
Different features: ['usertag']
  usertag: ['10063', '10063,13866']

BidID: 261909104ab7a1a6cb8f2aa3b12be1da
Different features: ['useragent']
  useragent: ['other_other', 'windows_ie']

BidID: 261cb9fd21a1a0ca594da5cda39de1b4
Different features: ['usertag']
  usertag: ['10006,10110', '10063,10111']

BidID: 2676d25efcc9121e6570a2a5f71e67a4
Different features: ['useragent', 'usertag']
  useragent: ['other_other', 'windows_ie']
  usertag: ['13800,10006,10110', '10006,13042,10031']

BidID: 2688c03bacc48edf78205d727cc6486d
Different features: ['hour', 'useragent', 'usertag']
  hour: [15, 14]
  useragent: ['other_other', 'windows_ie']
  usertag: ['10063,10006,10059,10031,10110', '13403,10059,10063,10052,10031,10057,10006,10110']

BidID: 26eef3fe794773559ab947f10de1db6b
Different features: ['usertag']
  usertag: ['10063,10110', '10063']

BidID: 27315769acfbc10f0068f18b65839e8
Different features: ['usertag']
  usertag: ['10063,10110', '10111']

BidID: 27478ca26d24f6b98255089c76139092
Different features: ['usertag']
  usertag: ['10063,10006,10110', '10006,10063,10110']

BidID: 274821c749a28b93056d611bfcf00261
Different features: ['usertag']
  usertag: ['13866,10111', '10111']

BidID: 276c508547d7188958e6e9298d7dc709
Different features: ['usertag']
  usertag: ['13866,10111', '10006,13866,10111']

BidID: 27dac9f5fa2eb2b462600b3d34a14e4
Different features: ['usertag']
  usertag: ['10063,10006,10110', '10006,10110']

BidID: 27f2b8d4588ec8dbea1afae0a5fbe88f
Different features: ['usertag']
  usertag: ['10063', '10006,10110']

BidID: 298473e8ec2b33b654aa87e912515b7d
Different features: ['usertag']
  usertag: ['10063,10110', '10063,10111']

BidID: 2a12c33308e3717d60b6b30df9afbd29
Different features: ['useragent']
  useragent: ['other_other', 'windows_ie']

BidID: 2a2a85b12c870f2234ffc2c5de46b765
Different features: ['usertag']
  usertag: ['13866,10111', '11379,10052,13866,10111']

BidID: 2aacbc5728b736a6b4282a1865e9e9ce
Different features: ['useragent', 'usertag']
  useragent: ['other_other', 'windows_ie']
  usertag: ['13866,10111', '10063,13866,10006,10111']

BidID: 2abffd33b7929c84dbb281cc12446d73
Different features: ['usertag']
  usertag: ['10063', '10059,10063,10006,10111']

BidID: 2ac47087ece88cd5dfda9c4f5dd7d48a
Different features: ['usertag']
  usertag: ['13866,10024', '10024']

BidID: 2b0c5cb0e5acfba718de31f4067fb00e
Different features: ['usertag']
  usertag: ['10006,10110', '10024,13800']

BidID: 2bad5991eaa605f1dcf4852a23c8b549
Different features: ['usertag']
  usertag: ['10063,10006,10110', '10006,10110']

BidID: 2bce783f80b9105e5f990f2880617009
Different features: ['useragent', 'usertag']
  useragent: ['other_other', 'windows_ie']
  usertag: ['10006,10110', '10006,10059,13866,10063,10075,10110']

BidID: 2bee0f718d25ce6dc6ed87ed7adcae84
Different features: ['usertag']
  usertag: ['10063,10006,10110', '10006,10110']

BidID: 2bffebbd6761b82cc3d96c325d293c14
Different features: ['useragent', 'usertag']
  useragent: ['windows_ie', 'other_other']
  usertag: ['13866,10063,10111', '13866,10111']

BidID: 2c851ae9b46d7516d98a20c11185f4b7
Different features: ['usertag']
  usertag: ['10006,10110', '10006,14273,10063,10075,10052,10684,10110']

BidID: 2cbf687a47868e2cb3c2fd6cd4aa7cff
Different features: ['usertag']
  usertag: ['10006,10110', '10077,10006,10063,10110']

BidID: 2d85a2e32f4043f81a09e545278d893
Different features: ['hour', 'useragent']
  hour: [2, 1]
  useragent: ['other_other', 'android_safari']

BidID: 2df05af34d8f93a5f64dc045f21d0953
Different features: ['usertag']
  usertag: ['13866,10111', '10083,10006,10024,10110']

BidID: 2df2a0680bd684b6abf968b4a6bff0fa
Different features: ['usertag']
  usertag: ['13866,10111', '10077,13866,10111']

BidID: 2e1d5ed2146e0a024033367e9d1712cd
Different features: ['usertag']
  usertag: ['10075,10006,10076,10110', '10006,10063,10057,10110']

BidID: 2e41e9ffb7411d74f03ac6a7624f1eb7
Different features: ['usertag']
  usertag: ['10063', '10006']

BidID: 2eb0f982e280cca3948fc90342fb9d
Different features: ['usertag']
  usertag: ['10063,13866,13678,10024,10111', '10024']

BidID: 2f2d920faa760f7b221ee5ea296db957
Different features: ['usertag']
  usertag: ['10006,10110', '10059,10057,10006,10111']

BidID: 2f6e33fdd858f3eb47c98e18c6e125bd
Different features: ['usertag']
  usertag: ['13800', '10006,13800']

BidID: 2f8ecb08ffc5b1c83aff7e182c3e0799
Different features: ['usertag']
  usertag: ['13866', '10057,10031,10110']

BidID: 305dd73365b3b254118b42c3aebf7e72
Different features: ['usertag']
  usertag: ['13866,10063', '13866']

BidID: 3089d5636402e369c3c2b0c782f904f6
Different features: ['usertag']
  usertag: ['10006,10110', '10063']

BidID: 3218bee4a31a3eb267331c0ef3f830b6
Different features: ['usertag']
  usertag: ['10052,14273,10063,10110', '13403,14273,10052,10063,10031,10006,13042,10057,10079,10684,10074,10059,10024,10110']

BidID: 325020ceaee89796c968ff89a32ae1c6
Different features: ['usertag']
  usertag: ['10006,10110', '10031,10074,10083,10006,13403,13042,10063,10059,10110']

BidID: 329ba9daf448e3194d76ba88b6ee2aca
Different features: ['usertag']
  usertag: ['10006,10110', '10057,10083,10006,10063,10110']

BidID: 32d04a350029601b068424ee2a8833a2
Different features: ['usertag']
  usertag: ['10063', '13866']

BidID: 32e6a6a093096ab80c68573d3b66912b
Different features: ['usertag']
  usertag: ['10063', '10063,10111']

BidID: 33003ba5d2c9a6847b70af5281c66907
Different features: ['usertag']
  usertag: ['13866,10006,10110', '10006,10075,10024,10063,13800,13866']

BidID: 344b0187a11c6fe06e2c4e1693de7399
Different features: ['usertag']
  usertag: ['10083,10110', '10059,10075,10083,10024,10006,10063,10057,10110']

BidID: 3491b7af3ee4764b1cf409c45653f1d8
Different features: ['usertag']
  usertag: ['10006,10110', '10006,10059,13403,10063,10110']

BidID: 359d994f5c20db08efe1b1f8126a96b2
Different features: ['usertag']
  usertag: ['10063', '10063,10110']

BidID: 359ef6d3814f8c7a7b43bece81a72a94
Different features: ['usertag']
  usertag: ['13403', '10006']

BidID: 35e7a2db05931327b2ec6fed3c25d4a0
Different features: ['usertag']
  usertag: ['10031,10110', '13042,10057,10006,10063,10024,10031,10110']

BidID: 3629820d85008768402074a089d634b0
Different features: ['usertag']
  usertag: ['10006,10063,10110', '10006,10110']

BidID: 36360e6c8b6c79b32db31fbf0ad77658
Different features: ['usertag']
  usertag: ['10063', '10059,10111']

BidID: 364f808f23016d13add848e9992fcf98
Different features: ['usertag']
  usertag: ['10006,10110', '10063,10111']

BidID: 3731adbc9b84bacec19a99f2950e34d8
Different features: ['usertag']
  usertag: ['10063', '10006,10031,13042,10063,10111']

BidID: 378e7de8f4f7c1d3e4f0bf98c96ab315
Different features: ['usertag']
  usertag: ['10063,10059,10111', '10024']

BidID: 38168f43fdcd47028ed32edd31690e8f
Different features: ['usertag']
  usertag: ['13866,10111', '10083,13866,10006,10110']

BidID: 38840737661fa90bfa6024c67e60b99d
Different features: ['hour']
  hour: [22, 21]

BidID: 389a4522d4cf2518641f2f0d5adc0be7
Different features: ['usertag']
  usertag: ['10006,10063,10110', '10063,10006']

BidID: 38d1e8aec944a14a6c985af41388ffe4
Different features: ['usertag']
  usertag: ['10063', '10063,10111']

BidID: 38fec0c8cb88b35ce262bc988ab7dd33
Different features: ['usertag']
  usertag: ['10006,10110', '10063,10083,10052,10057,10059,10006,13403,10024,10110']

BidID: 395fdaadceb32520727a2a43af9e4f6d
Different features: ['usertag']
  usertag: ['13866,10111', '13866,10063,10111']

BidID: 3964f4ac8c04861c3c429d73917cb186
Different features: ['usertag']
  usertag: ['10006,10110', '10024,10006']

BidID: 39863abfe0bbac3cb9656ae9c4c3d5a3
Different features: ['usertag']
  usertag: ['10006,10110', '10076,10063,10059,10075,10006,10111']

BidID: 39fb77fbad87bfcf4979aae68464a179
Different features: ['usertag']
  usertag: ['10063', '10077,10063,10111']

BidID: 3a18dfbca54641fe137e0929338d39ce
Different features: ['usertag']
  usertag: ['13800,10063,10111', '13800']

BidID: 3a1b0972f788e15a3e9584b29ce1ffed
Different features: ['usertag']
  usertag: ['10006,10110', '13042,10031']

BidID: 3a40b3ade33d572cc371bd82ce5a27f2
Different features: ['useragent']
  useragent: ['windows_ie', 'other_other']

BidID: 3a5a1d9c4f2a795c7ce0040b0ad13791
Different features: ['usertag']
  usertag: ['10006,10063,10110', '10111']

BidID: 3af6c078c18cc76eb59e4daef5c452c3
Different features: ['usertag']
  usertag: ['10063,10006,10110', '13042,10075,13403,10031,10063,10059,10006,10111']

BidID: 3b1248b4ee524265ae8f925bc6a49166
Different features: ['useragent']
  useragent: ['other_other', 'mac_other']

BidID: 3b997eb3f23f61989cb37b798d1b0a04
Different features: ['usertag']
  usertag: ['10063', '10063,10006,10024']

BidID: 3bc1d1248d27dd3256045d92c61d9074
Different features: ['usertag']
  usertag: ['10063', '13866,10063,10110']

BidID: 3bd11d71146e4c6a6683aaff39505acd
Different features: ['usertag']
  usertag: ['10063,10006,10110', '10006']

BidID: 3bd28dfd46cfcdb87385ddaa14ca1c3c
Different features: ['usertag']
  usertag: ['13866,10111', '13866,10059,10063,10111']

BidID: 3c13a29c4f8f284e93e4ef24d5205511

In [26]:
dict

{'usertag': 756, 'useragent': 134, 'hour': 37, 'payprice': 6}

In [27]:
import numpy as np

# Randomly select one row for each bidid
random_rows = df_duplicated.groupby("bidid").sample(n=1, random_state=42)

# Combine all usertags for each bidid
combined_tags = (
    df_duplicated.groupby("bidid")["usertag"]
      .apply(lambda x: ",".join(sorted(set(
          tag
          for value in x.dropna()
          for tag in value.split(",")
      ))))
)

# Replace the usertag in the randomly selected rows
random_rows["usertag"] = random_rows["bidid"].map(combined_tags)

# Result
df_combined = random_rows.reset_index(drop=True)

In [28]:
df_combined # shouldn't we be left with 5,000+, the number of unique bids
# out of the duplicates

,click,weekday,hour,bidid,timestamp,logtype,ipinyouid,useragent,IP,region,...,slotheight,slotvisibility,slotformat,slotprice,creative,bidprice,payprice,keypage,advertiser,usertag
0,0,3,14,10017f7b042216349d89dfe7d9ada3a7,20130612141014982,1,Vh5zP3p63U8fjQc,windows_chrome,106.86.23.*,275,...,280,0,1,0,77819d3e0b3467fe5c7b16d68ad923a1,300,151,bebefa5efe83beee17a3d245e7c5085b,1458,
1,0,3,20,1007fdd9a74414192a03c9bd77202a0a,20130612204208020,1,Vh5zLxl9OHEIjZa,windows_chrome,218.75.146.*,201,...,90,1,0,5,48f2e9ba15708c0146bda5e1dd653caa,300,15,bebefa5efe83beee17a3d245e7c5085b,1458,"10063,10111"
2,0,3,15,100df7877c81acfdf999e1a0ee1eb73f,20130612152514254,1,Vhk0CDpqD4xUFGn,windows_chrome,125.85.66.*,275,...,280,2,0,4,77819d3e0b3467fe5c7b16d68ad923a1,300,4,bebefa5efe83beee17a3d245e7c5085b,1458,"10006,10063,10102,10110"
3,0,1,0,1014d5f55911b7186f9af6462c9911f0,20130610000104347,1,VhkyOaCx3QTLjMR,windows_chrome,101.85.56.*,79,...,280,0,1,0,77819d3e0b3467fe5c7b16d68ad923a1,300,77,bebefa5efe83beee17a3d245e7c5085b,1458,10063
4,0,0,20,1014ef29721f3210bbd540fd52e50a3f,20130609200033260,1,VhkyLuMoD812Qhk,windows_ie,221.214.216.*,146,...,250,1,0,5,2abc9eaf57d17a96195af3f63c45dc72,300,77,bebefa5efe83beee17a3d245e7c5085b,1458,13866
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5597,0,0,14,ffb7f078a336d4b4868973c158dcf9a0,20130609142515038,1,VhkROu55ONFc3oL,windows_ie,110.240.218.*,3,...,280,2,0,5,77819d3e0b3467fe5c7b16d68ad923a1,300,157,bebefa5efe83beee17a3d245e7c5085b,1458,"10024,10076"
5598,0,2,2,ffc9d07883e6c681c69e87bb85b1622b,20130611022107521,1,Z0T1LnjxLenygIl,windows_chrome,14.127.210.*,216,...,90,0,0,80,832b91d59d0cb5731431653204a76c0e,300,80,bebefa5efe83beee17a3d245e7c5085b,1458,"10006,10024,10031,10052,10057,10063,10083,1011..."
5599,0,4,15,ffcd02157f67a5b8f9674c787b7f66a1,20130606154517713,1,Vhk7PuuTDvNPu-b,windows_chrome,114.83.119.*,79,...,280,2,1,0,77819d3e0b3467fe5c7b16d68ad923a1,300,168,bebefa5efe83beee17a3d245e7c5085b,1458,
5600,0,2,22,ffd18d8da34b791144eb0b2cf09aa726,20130611223507358,1,Vh16OvTbO6FTjmR,other_other,222.178.10.*,275,...,600,2,1,0,cb7c76e7784031272e37af8e7e9b062c,300,61,bebefa5efe83beee17a3d245e7c5085b,1458,"10024,10063,10111,13800,13866"
5601,0,0,22,ffe5ca334ac7d104fa90cc0f84b86817,20130609224007079,1,Vhky15L8OtBWF-c,windows_chrome,163.125.50.*,216,...,60,2,0,5,612599432d200b093719dd1f372f7a30,300,6,bebefa5efe83beee17a3d245e7c5085b,1458,

5602, the magic number

## Combine the cleaned duplicates with the original data

In [31]:
# remove all original rows whose bidid has been tidied 
df_clean = df[~df['bidid'].isin(df_combined['bidid'])].copy()

# append the tidied duplicates back in 
df_clean = pd.concat(
    [df_clean, df_combined],
    ignore_index=True
)

In [35]:
df_clean[df_clean.duplicated()]

Empty DataFrame
Columns: [click, weekday, hour, bidid, timestamp, logtype, ipinyouid, useragent, IP, region, city, adexchange, domain, url, urlid, slotid, slotwidth, slotheight, slotvisibility, slotformat, slotprice, creative, bidprice, payprice, keypage, advertiser, usertag]
Index: []

[0 rows x 27 columns]

0 rows :)